Updates status checker script to fix early exit in degraded status that prevented all fails.

diff --git a/scripts/status b/scripts/status
--- a/scripts/status
+++ b/scripts/status
@@ -19,7 +19,7 @@ checkAllServices() {
     [[ -f "${projPath}/${app}/configs.json" ]] && serviceStatus $app
   done
   echo -e "\n\n"
-  [[ $serviceCount -gt $aliveCount ]] && echo -e "✗ Partially degraded" && exit 1 || [[ $aliveCount -eq 0 ]] && echo -e "✗ All failed." && exit 1 || echo -e "\xE2\x9C\x94 All services up." && exit 0
+  [[ $aliveCount -eq 0 ]] && echo -e "✗ All failed." && exit 1 || [[ $serviceCount -gt $aliveCount ]] && echo -e "✗ Partially degraded" && exit 1 || echo -e "\xE2\x9C\x94 All services up." && exit 0
 }
 
 [[ ! -z $1 ]] && serviceStatus $1 && exit 0 || checkAllServices
