Adds fix for port json parsing and reinstates service restart on degraded health.

diff --git a/scripts/status b/scripts/status
--- a/scripts/status
+++ b/scripts/status
@@ -12,7 +12,7 @@ serviceStatus() {
   elif [[ $1 == 'dash' ]]; then
     port=5174
   else
-    port=$(cat "${projPath}/$1/configs.json" | jq '.app.port')
+    [[ -f "${projPath}/$1/configs.json" ]] && port=$(cat "${projPath}/$1/configs.json" | jq '.app.port') || port=''
   fi
   [[ -z $port ]] && return 1
   _pid=$(lsof -i ":${port}" | grep -v "PID" | awk '{print $2}' | uniq | tr '\n' ' ' | sed 's/ $//g')
@@ -31,8 +31,8 @@ checkAllServices() {
   for app in $(ls $projPath); do
     [[ -f "${projPath}/${app}/package.json" ]] && [[ $app != 'utils' ]] && serviceStatus $app
   done
-  echo -e "\n\n"
-  # [[ $aliveCount -eq 0 ]] && echo -e "✗ All failed." && bringServicesUp && exit 1 || [[ $serviceCount -gt $aliveCount ]] && echo -e "✗ Partially degraded [$aliveCount/$serviceCount]" && bringServicesUp && exit 1 || echo -e "\xE2\x9C\x94 All services up." && exit 0
+  # echo -e "\n\n"
+  [[ $aliveCount -eq 0 ]] && echo -e "✗ All failed." && bringServicesUp && exit 1 || [[ $serviceCount -gt $aliveCount ]] && echo -e "✗ Partially degraded [$aliveCount/$serviceCount]" && bringServicesUp && exit 1 || echo -e "\xE2\x9C\x94 All services up." && exit 0
 }
 
 [[ ! -z $1 ]] && serviceStatus $1 && exit 0 || checkAllServices
