Adds a cleaner handling of service count.

diff --git a/scripts/status b/scripts/status
--- a/scripts/status
+++ b/scripts/status
@@ -12,14 +12,14 @@ serviceStatus() {
 
 checkAllServices() {
   for app in $(ls $projPath); do
-    [[ -s "${projPath}/${app}/configs.json" ]] && serviceCount=$(($serviceCount+1))
+    [[ $app == "admin" ]] || [[ -s "${projPath}/${app}/configs.json" ]] && serviceCount=$(($serviceCount+1))
   done
   echo -e "[$(date '+%Y-%m-%dT%T')] Service [Status | Port | PID]" &&
   for app in $(ls $projPath); do
     [[ -f "${projPath}/${app}/package.json" ]] && [[ $app != 'utils' ]] && serviceStatus $app
   done
   echo -e "\n\n"
-  [[ $aliveCount -eq 0 ]] && echo -e "✗ All failed." && exit 1 || [[ $serviceCount -gt $aliveCount ]] && echo -e "✗ Partially degraded" && exit 1 || echo -e "\xE2\x9C\x94 All services up." && exit 0
+  [[ $aliveCount -eq 0 ]] && echo -e "✗ All failed." && exit 1 || [[ $serviceCount -gt $aliveCount ]] && echo -e "✗ Partially degraded [$aliveCount/$serviceCount]" && exit 1 || echo -e "\xE2\x9C\x94 All services up." && exit 0
 }
 
 [[ ! -z $1 ]] && serviceStatus $1 && exit 0 || checkAllServices
